apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver
spec:
  replicas: 3
  selector:
    matchLabels:
      app: timeserver-pod
  template:
    metadata:
      labels:
        app: timeserver-pod
    spec:
      priorityClassName: high-priority
      containers:
      - name: timeserver-container
        image: bilegtbd/server:latest
        resources:
          requests:
            cpu: 200m
            memory: 250Mi
