apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeserver-env
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: timeserver-pod
  template:
    metadata:
      labels:
        pod: timeserver-pod
    spec:
      containers:
      - name: timeserver-container
        image: bilegtbd/server:2
        env:
        - name: AVATAR_ENDPOINT
          value: http://$(ROBOHASH_INTERNAL_SERVICE_HOST)
